Update validationErrorStatus.json
veraPDF/verapdf-webapp-gui pull request #231
Opened 2022-10-21 17:02 UTC by jzuidweg

This is a comprehensive update of the file validationErrorStatus.json. Added the error status for WCAG rules 4.1.2-27 to 4.1.2-45 and PDF/UA-1 rule 7.18.4-2.

2022-10-24 09:59 UTC, MaximPlusov requested changes

2022-10-24 09:59 UTC, MaximPlusov commented on src/common/components/layouts/pages/inspect/validationErrorStatus.json
> +        "RATIONALE": "A merged cell must be tagged correctly corresponding to the amount of columns it spans."
This errors may also be for non merged cells.

2022-10-24 09:59 UTC, MaximPlusov commented on src/common/components/layouts/pages/inspect/validationErrorStatus.json
> +        "RATIONALE": "If dynamic forms are not tagged properly, reader software may not know how to handle them."
We changed dynamic to interactive several weeks ago.

2022-10-24 09:59 UTC, MaximPlusov commented on src/common/components/layouts/pages/inspect/validationErrorStatus.json
> +        "RATIONALE": "A single list should be tagged as such and not a series of smaller lists."
It may be not tagged as several lists. It could be several paragraphs, spans, or else structure elements.

2022-10-24 09:59 UTC, MaximPlusov commented on src/common/components/layouts/pages/inspect/validationErrorStatus.json
> +        "RATIONALE": "Table of content items should point somwhere in the document."
somwhere -> somewhere.
It's rule not about link, it's about toci page label. Maybe we need to write a more understandable message

2022-10-24 10:05 UTC, jzuidweg commented
Thanks Maxim for the review of my error messages. I will have a look at the issues you raised and think of alternative phrasing.

2022-10-25 13:56 UTC, jzuidweg commented
I have implemented the changes you suggested an will generate a new pull request.

2022-10-25 13:56 UTC, closed without merging