Adding errors grouping
veraPDF/verapdf-webapp-gui pull request #302
Opened 2023-11-28 13:16 UTC by GribovskyPavel

2023-11-29 08:21 UTC, ekaterina-chubrick requested changes

2023-11-29 08:21 UTC, ekaterina-chubrick commented on src/common/components/layouts/pages/inspect/Inspect.js
> +export const TAGS = _.flatMap(_.entries(errorTags), category => category[1]);
This mapping can be replaced with a more readable one: `_.chain(a).values().flatten().value()`.

2023-11-29 08:21 UTC, ekaterina-chubrick commented on src/common/components/layouts/pages/inspect/Inspect.js
> +        setExpandedGroups(new Array(errorTags[selectedGroup].length + 1).fill(UNSELECTED).map((_, index) => index));
_Minor:_ We can skip the step with filling an array with empty values: `Array.from(Array(errorTags[selectedGroup].length + 1).keys())`

2023-11-30 07:45 UTC, KateOrient approved these changes

2023-11-30 14:28 UTC, merged